"use strict";

// Regression tests for bin/gsd-t-schema-id-check.cjs — the integer-identity
// primary-key verify gate.
//
// The load-bearing behaviours:
//   1. A NEW table without an integer identity PK FAILS.
//   2. A NEW table with one PASSES (all three Postgres spellings).
//   3. A COMMITTED table without one is IGNORED — the rule is new-tables-only,
//      because repointing an existing UUID PK's foreign keys is a data migration
//      + Destructive Action Guard item, not an in-passing edit.
//   4. A repo with no new schema files is a no-op PASS distinguishable from a
//      wired-but-broken FAIL (no silent degradation).

const { test } = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { execFileSync } = require("node:child_process");

const {
  check,
  extractSqlTables,
  sqlTableHasIntegerIdPk,
  extractPrismaModels,
  prismaModelHasIntegerIdPk,
} = require("../bin/gsd-t-schema-id-check.cjs");

// ─── Detector unit tests (no git, no fs) ─────────────────────────────────────

test("SQL: identity PK spellings are accepted", () => {
  const cases = [
    "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, x TEXT);",
    "CREATE TABLE t (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, x TEXT);",
    "CREATE TABLE t (id BIGSERIAL PRIMARY KEY, x TEXT);",
    "CREATE TABLE t (id SERIAL PRIMARY KEY, x TEXT);",
    // table-level constraint form
    "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY, x TEXT, PRIMARY KEY (id));",
  ];
  for (const sql of cases) {
    const [tbl] = extractSqlTables(sql);
    assert.equal(sqlTableHasIntegerIdPk(tbl.body), true, sql);
  }
});

test("SQL: UUID / text / composite primary keys are rejected", () => {
  const cases = [
    "CREATE TABLE t (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), x TEXT);",
    "CREATE TABLE t (id TEXT PRIMARY KEY, x TEXT);",
    "CREATE TABLE t (order_id BIGINT, sku TEXT, PRIMARY KEY (order_id, sku));",
    // integer id present but NOT the primary key
    "CREATE TABLE t (id BIGINT, uid UUID PRIMARY KEY, x TEXT);",
  ];
  for (const sql of cases) {
    const [tbl] = extractSqlTables(sql);
    assert.equal(sqlTableHasIntegerIdPk(tbl.body), false, sql);
  }
});

test("SQL: nested type parens do not truncate the table body", () => {
  const sql =
    "CREATE TABLE t (amount NUMERIC(10,2) NOT NULL, id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY);";
  const [tbl] = extractSqlTables(sql);
  assert.ok(tbl.body.includes("NUMERIC(10,2)"));
  assert.equal(sqlTableHasIntegerIdPk(tbl.body), true);
});

test("SQL: multiple tables in one file are each extracted", () => {
  const sql = `
    CREATE TABLE a (id BIGSERIAL PRIMARY KEY);
    CREATE TABLE IF NOT EXISTS b (id UUID PRIMARY KEY);
  `;
  const tables = extractSqlTables(sql);
  assert.equal(tables.length, 2);
  assert.equal(sqlTableHasIntegerIdPk(tables[0].body), true);
  assert.equal(sqlTableHasIntegerIdPk(tables[1].body), false);
});

test("Prisma: autoincrement Int/BigInt id accepted, uuid/cuid rejected", () => {
  const good = "model U {\n id Int @id @default(autoincrement())\n}";
  const goodBig = "model U {\n id BigInt @id @default(autoincrement())\n}";
  const badUuid = "model U {\n id String @id @default(uuid())\n}";
  const badCuid = "model U {\n id String @id @default(cuid())\n}";
  assert.equal(prismaModelHasIntegerIdPk(extractPrismaModels(good)[0].body), true);
  assert.equal(prismaModelHasIntegerIdPk(extractPrismaModels(goodBig)[0].body), true);
  assert.equal(prismaModelHasIntegerIdPk(extractPrismaModels(badUuid)[0].body), false);
  assert.equal(prismaModelHasIntegerIdPk(extractPrismaModels(badCuid)[0].body), false);
});

// ─── Integration tests (real git repo in a temp dir) ─────────────────────────

function tmpRepo() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "gsdt-schema-id-"));
  execFileSync("git", ["init", "-q", "."], { cwd: dir, stdio: "ignore" });
  return dir;
}
function write(dir, rel, body) {
  const abs = path.join(dir, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, body);
}
function commitAll(dir) {
  execFileSync("git", ["add", "-A"], { cwd: dir, stdio: "ignore" });
  execFileSync(
    "git",
    ["-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "x"],
    { cwd: dir, stdio: "ignore" }
  );
}

test("NEW table without an integer identity PK FAILS", () => {
  const dir = tmpRepo();
  write(dir, "migrations/001.sql", "CREATE TABLE orders (id UUID PRIMARY KEY, total NUMERIC);");
  const res = check(dir);
  assert.equal(res.ok, false);
  assert.equal(res.failures.length, 1);
  assert.match(res.failures[0], /orders/);
  assert.match(res.failures[0], /IDENTITY PRIMARY KEY/);
  fs.rmSync(dir, { recursive: true, force: true });
});

test("NEW table with an integer identity PK PASSES", () => {
  const dir = tmpRepo();
  write(
    dir,
    "migrations/001.sql",
    "CREATE TABLE orders (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, public_id UUID NOT NULL DEFAULT gen_random_uuid());"
  );
  const res = check(dir);
  assert.equal(res.ok, true);
  assert.equal(res.failures.length, 0);
  assert.equal(res.inspected.length, 1);
  fs.rmSync(dir, { recursive: true, force: true });
});

test("COMMITTED non-compliant table is IGNORED — rule is new-tables-only", () => {
  const dir = tmpRepo();
  write(dir, "migrations/000_legacy.sql", "CREATE TABLE legacy (id UUID PRIMARY KEY);");
  commitAll(dir);
  const res = check(dir);
  assert.equal(res.ok, true, "an established UUID-keyed schema must not fail the gate");
  assert.equal(res.inspected.length, 0);
  fs.rmSync(dir, { recursive: true, force: true });
});

test("repo with no schema changes is an explicit no-op PASS, not a silent one", () => {
  const dir = tmpRepo();
  write(dir, "README.md", "# hi");
  const res = check(dir);
  assert.equal(res.ok, true);
  assert.match(res.note, /no-op PASS/);
  fs.rmSync(dir, { recursive: true, force: true });
});

test("non-git directory is an explicit no-op PASS naming the reason", () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "gsdt-schema-id-nogit-"));
  write(dir, "migrations/001.sql", "CREATE TABLE t (id UUID PRIMARY KEY);");
  const res = check(dir);
  assert.equal(res.ok, true);
  assert.match(res.note, /git unavailable|not a repository/);
  fs.rmSync(dir, { recursive: true, force: true });
});

test("NEW Prisma model without an autoincrement id FAILS", () => {
  const dir = tmpRepo();
  write(dir, "prisma/schema.prisma", "model User {\n  id String @id @default(uuid())\n}");
  const res = check(dir);
  assert.equal(res.ok, false);
  assert.match(res.failures[0], /model `User`/);
  assert.match(res.failures[0], /autoincrement/);
  fs.rmSync(dir, { recursive: true, force: true });
});
